BeerShop/Controllers/BeerController.cs
using AutoMapper;
using BeerShop.Domains.EntitiesDB;
using BeerShop.Services;
using BeerShop.Services.Interfaces;
using BeerShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BeerShop.Controllers
{
    public class BeerController : Controller
    {
        private readonly IBeerService _beerService;
        private readonly IMapper _mapper;
        private IService<Brewery> _breweryService;
        private IService<Variety> _varietyService;

        public BeerController(IBeerService beerService, IMapper mapper, IService<Brewery> breweryService, IService<Variety> varietyService)
        {
            _mapper = mapper;
            _beerService = beerService;
            _breweryService = breweryService;
            _varietyService = varietyService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var beers = await _beerService.GetAllAsync();
                List<BeerVM>? beerVMs = null;

                if (beers != null)
                {
                    beerVMs = _mapper.Map<List<BeerVM>>(beers);
                }
                return View(beerVMs);
            }
            catch (Exception ex)
            {
                // Log the error (consider a logging framework)
                ModelState.AddModelError("", "Er is een fout opgetreden bij het ophalen van de bedrijven: " + ex.Message);
            }
            return View();
        }

        public IActionResult GetBeerByAlcohol()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetBeersByAlcohol(BeerSearchByAlcoholVM model)
        {
            if (ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                var beers = await _beerService.GetBeersByAlcohol(model.AlcoholPercentage!.Value);
                model.Beers = _mapper.Map<List<BeerVM>>(beers);
                return View(model);
            }
            catch (Exception ex)
            {
                // Log the error (consider a logging framework)
                ModelState.AddModelError("", "Er is een fout opgetreden bij het ophalen van de bieren: " + ex.Message);
                return View();
            }
        }

        public async Task<IActionResult> GetBeersByBreweries()
        {
            try
            {
                ViewBag.lstBrouwer = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam"
                    );
                return View();
            }
            catch (Exception ex)
            {
                // Log the error (consider a logging framework)
                //ModelState.AddModelError("", "Er is een fout opgetreden bij het ophalen van de brouwerijen: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> GetBeersByBreweries(int? brouwerID)
        {
            if (brouwerID == null)
            {
                return NotFound();
            }
            try
            {
                var bierlijst = await _beerService.GetBeersByBreweries(Convert.ToInt16(brouwerID));

                ViewBag.lstBrouwer = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam",
                    brouwerID
                    );

                List<BeerVM> listVM = _mapper.Map<List<BeerVM>>(bierlijst);
                return View(listVM);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public async Task<IActionResult> GetBeersByBreweriesVM()
        {
            try
            {
                BreweryBeersVM breweryBeersVM = new BreweryBeersVM();


                breweryBeersVM.Breweries = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam"
                    );
                return View(breweryBeersVM);
            }
            catch (Exception ex)
            {
                // Log the error (consider a logging framework)
                //ModelState.AddModelError("", "Er is een fout opgetreden bij het ophalen van de brouwerijen: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> GetBeersByBreweriesVM(BreweryBeersVM entity)
        {
            if (entity.BreweryNumber == null)
            {
                return NotFound();
            }
            try
            {
                var bierlijst = await _beerService.GetBeersByBreweries(Convert.ToInt16(entity.BreweryNumber));

                ViewBag.lstBrouwer = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam",
                    entity.BreweryNumber
                    );
                entity.Beers = _mapper.Map<List<BeerVM>>(bierlijst);
                entity.Breweries = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam",
                    entity.BreweryNumber
                    );
                return View(entity);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public async Task<IActionResult> GetBeersByBreweriesAjax()
        {
            try
            {
                BreweryBeersVM breweryBeersVM = new BreweryBeersVM();


                breweryBeersVM.Breweries = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam"
                    );
                return View(breweryBeersVM);
            }
            catch (Exception ex)
            {
                // Log the error (consider a logging framework)
                //ModelState.AddModelError("", "Er is een fout opgetreden bij het ophalen van de brouwerijen: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> GetBeersByBreweriesAjax(BreweryBeersVM entity)
        {
            if (entity.BreweryNumber == null)
            {
                return NotFound();
            }
            try
            {
                var beerLst = await _beerService.GetBeersByBreweries
               (Convert.ToInt16(entity.BreweryNumber));
                List<BeerVM> listVM = _mapper.Map<List<BeerVM>>(beerLst);

                // er moet geen lijst met brouwers worden meegegeven

                return PartialView("_SearchBierenPartial", listVM);

            }
            catch
            {

            }
            return View(entity);

        }

        public async Task<IActionResult> Create()
        {

            try
            {
                var beerCreate = new BeerBaseCRUD()
                {
                    Breweries = new SelectList(await _breweryService.GetAllAsync(),
                    "Brouwernr", "Naam"),
                    Varieties = new SelectList(await _varietyService.GetAllAsync(),
                    "Soortnr", "Soortnaam")
                };
                return View(beerCreate);
            }
            catch (Exception ex)
            {
                //iets
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BeerBaseCRUD model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var beerEntity = _mapper.Map<Beer>(model);
                    await _beerService.AddAsync(beerEntity);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                //iets
                throw;
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var beer = await _beerService.FindByIdAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<BeerEditVM>(beer);
            model.Breweries = new SelectList(await _breweryService.GetAllAsync(),
                "Brouwernr", "Naam", model.Brouwernr);
            model.Varieties = new SelectList(await _varietyService.GetAllAsync(),
                "Soortnr", "Soortnaam", model.Soortnr);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BeerEditVM model)
        {
            if (id != model.Biernr)
            {
                return NotFound();
            }
            try
            {
                if (ModelState.IsValid)
                {
                    var beer = _mapper.Map<Beer>(model);
                    await _beerService.UpdateAsync(beer);
                    return RedirectToAction(nameof(Index));
                }

                // dropdowns opnieuw vullen bij fout
                model.Breweries = new SelectList(
                    await _breweryService.GetAllAsync(),
                    "Brouwernr",
                    "Naam",
                    model.Brouwernr);

                model.Varieties = new SelectList(
                    await _varietyService.GetAllAsync(),
                    "Soortnr",
                    "Soortnaam",
                    model.Soortnr);

                return View(model);
            }
            catch (Exception ex)
            {
                //iets
                throw;

            }

        }


        public async Task<IActionResult> Delete(int id)
        {

BeerShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerShop</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeerShop.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeerShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="Index">Beer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="GetBeerByAlcohol">BeerByAlcohol</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="GetBeersByBreweries">GetBeersByBreweries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="GetBeersByBreweriesVM">GetBeersByBreweriesVM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="GetBeersByBreweriesAjax">GetBeersByBreweriesAjax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beer" asp-action="Create">CreateBeer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BeerShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>